version: '3'
services:
  node_1_service_a:
    restart: always
    build:
      context: .
      dockerfile: ./src/evaluation/docker/distributed_system/service_a/Dockerfile
  node_2_services_b_c:
    restart: always
    build:
      context: .
      dockerfile: ./src/evaluation/docker/distributed_system/service_b_c/Dockerfile
    expose:
      - 1234
  node_3_services_d:
    restart: always
    build:
      context: .
      dockerfile: ./src/evaluation/docker/distributed_system/service_d/Dockerfile
    expose:
      - 1234
  collector:
    restart: always
    build:
      context: .
      dockerfile: ./src/evaluation/docker/collector/Dockerfile
    ports:
      - "8080:80"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: collector
    ports:
      - "3305:3306"
    volumes:
      - ./src/implementation/collector/res/db/mysql/data:/var/lib/mysql
      - ./src/implementation/collector/res/db/mysql/init:/docker-entrypoint-initdb.d/:ro