version: '3'
services:
  service_a:
    tty: true
    environment:
      CFG: src/evaluation/cfg/service_a.yaml
    build:
      context: .
      dockerfile: ./src/evaluation/docker/distributed_system/a/Dockerfile
    volumes:
      - .:/code